### ISSUE TITLE
deprecate use of .off() with path argument

### ISSUE THREAD

**Issue by JensEggers** [happner/happner#107]
This applies to data and events (I believe): .off() called with a path removes all listeners .off() called with a handle removes only the listener identified by the handle. This is confusing and causes unexpected and hard to find problems. Instead, let us follow the Node.js convention: ``` emitter.removeListener(event, listener) emitter.removeAllListeners([event]) ``` Changes: - deprecate the use of .off() with a path argument - add a new function (.offAll() - haha, think of something better) that accepts only a path argument and removes all listeners

**Comment by JensEggers** [comment]
@southbite , please reference the relevant commit/PR so this issue can be reviewed & closed.

**Comment by southbite** [comment]
closed with PR https://github.com/happner/happner/pull/145
