### ISSUE TITLE
happner leaks process.on('uncaughtException') subscriptions

### ISSUE THREAD

**Issue by JensEggers** [happner/happner#110]
This happens in long mocha tests with multiple happner instances being created and destroyed. Eventually I see this warning: ``` (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit. ``` process is a global that lives for the duration of the Node.js process, and these subscriptions persist across mesh instances. The process subscriptions should be removed when the happner instance shuts down. Other process.on() subscriptions are also probably leaked: - 'exit' - 'SIGTERM' - 'SIGINT'

**Comment by southbite** [comment]
fixed in release 1.16.0
