### ISSUE TITLE
only load browserCrypto.js when needed

### ISSUE THREAD

**Issue by JensEggers** [happner/happner#117]
This module is costly to load and makes initial page loads feel slow. If I understand it right, we only need this module when doing payload encryption? If so, it should only be loaded if payload encryption has been configured on the server mesh.

**Comment by southbite** [comment]
working on this now, have all tests passing, except for the browser tests - may have found an issue the crypto library on the browser client

**Comment by JensEggers** [comment]
@southbite , please reference the relevant commit/PR so this issue can be reviewed & closed.
