### ISSUE TITLE
add REST API component to automatically expose exchange methods as REST API

### ISSUE THREAD

**Issue by JensEggers** [happner/happner#144]
09/05/16-JCE: Need to decide on underlying data architecture
- shared data component?
- data permissions?
- direct happn access?
- pass in identity to check permissions?
&nbsp;
Authentication will initially be token based, so login happens - a token is returned that can get reused for a set of calls.
The REST component can be configured to have a default authentication policy:
per session:
inactivity timeout:6000 (10 min)
call limit: infinite (0)
authentication policies can be set up per route, and per user, and per application code
for authentication we have 2 methods:
(1) username and password, get JWT back, the token is used for consecutive calls.
(2) application code, essentially an alias for a username and password
https://docs.google.com/document/d/1yZNN9sON5BSfuYqGrj7DxH6ZMKLq3OcIwusPN3NpclA/edit

**Comment by JensEggers** [comment]
make self-describing via HTTP OPTIONS request

follow a REST RPC formalism:

- component/method name in URL
- parameters as JSON payload
- response as JSON payload

**Comment by southbite** [comment]
done with release 1.20.1

**Comment by southbite** [comment]
for tests and docs go here:
https://github.com/happner/happner/blob/master/docs/restcomponent.md
https://github.com/happner/happner/blob/master/test/e3a-rest-component.js
https://github.com/happner/happner/blob/master/test/e3b-rest-component-secure.js
