### ISSUE TITLE
Increase coverage of testing.

### ISSUE THREAD

**Issue by JohanvdWest** [happner/happner#156]

**Comment by JensEggers** [comment]
where was the problem that you fixed without a test again?

**Comment by JensEggers** [comment]
this needs a reference to the untested code

**Comment by JohanvdWest** [comment]
This was raised by a bug in mesh_client.js, line 413.
This is the subscription handler for the mesh/schema/description.

**Comment by JohanvdWest** [comment]
Resolved in #162
