### ISSUE TITLE
$happn injection on local exchange inconsistent with remote exchange.

### ISSUE THREAD

**Issue by JohanvdWest** [happner/happner#202]
The local exchange forces callback to be last where the remote exchange will allow $happn after callback.

Callback last is a better convention, but this is a breaking change.

**Comment by JohanvdWest** [comment]
``` javascript
this.someFunction = function(options,callback,$happn) {
  callback();
}
```

This will not work on new exchange.

**Comment by nomilous** [comment]
Added tests. PR #203 

It appears to work fine.

Perhaps you can clarify exactly the circumstances that it is not working in.

**Comment by JohanvdWest** [comment]
Sorry, my bad. We can close this. Let's leave the test in there with the PR.

I think this came about due to changes I was making and I then jumped to the wrong conclusion.

**Comment by nomilous** [comment]
Cool.

**Comment by nomilous** [comment]
I think someone other than me should merge the PR.
