### ISSUE TITLE
add .once() subscriptions wherever we have .on()

### ISSUE THREAD

**Issue by JensEggers** [happner/happner#207]

**Comment by southbite** [comment]
Hi Jens - is this for exchange calls primarily? because once in my mind once subscriptions only happen once and then they are deleted.

**Comment by JensEggers** [comment]
Hi, yes that is the idea - for the subscriptions to be automatically
deleted. This is especially useful for testing as it means we don't have to
explicitly remove listeners at the end of a test. Would be useful for
event, data and shared data subscriptions.

**Comment by southbite** [comment]
oh right, so happn events - effectively you want a new once method

**Comment by JensEggers** [comment]
Yes that makes sense

**Comment by JensEggers** [comment]
closing, will only implement on happner-2
