### ISSUE TITLE
add security.addGroupPermissions to merge in new permissions

### ISSUE THREAD

**Issue by JensEggers** [happner/happner#227]

**Comment by JensEggers** [comment]
not sure this is a bug - but it would be very useful for components to be able to add permissions to a pre-existing group without overwriting existing permissions

**Comment by southbite** [comment]
ok - right, understanding this now - I think the permissions thing is by design, so you need to fetch the group, - add your permissions then save the group you fetched

**Comment by JensEggers** [comment]
makes sense - changing this issue to create an addGroupPermissions() function.
