### ISSUE TITLE
If the happner-loader child process fails to load, the happner-loader should retry

### ISSUE THREAD

**Issue by JohanvdWest** [happner/happner#240]

**Comment by cordellcalitz** [comment]
Two ways I can see to fix this:
1) add a fork.on('close') event listener
2) parse the messages to look for the "(Mesh) exit <code>" message

**Comment by JensEggers** [comment]
Also the spawn request can throw, as well as emit an 'error' event

**Comment by JohanvdWest** [comment]
The way to fix this would be to have happner-loader retry loading forever if the child.exit event is fired.

**Comment by JohanvdWest** [comment]
Fixed by #264
