### ISSUE TITLE
Shared datalayer emit on "set" should check if noPublish is set

### ISSUE THREAD

**Issue by JohanvdWest** [happner/happner#303]

**Comment by JensEggers** [comment]
... and then not emit

**Comment by southbite** [comment]
Hi chaps, this could also be a happner issue, but giving the code a glance I cannot see how this is happening, Johan - you wouldnt be able add a test, or a code snippet so I could understand how the set is being called?

**Comment by JensEggers** [comment]
Hi Simon, Johan's found the relevant place and will create a PR. Thx for
checking!

**Comment by JensEggers** [comment]
we haven't gotten to this yet. Here's the relevant code section:
https://github.com/happner/happner/blob/master/lib/modules/data/index.js#L16
```
Data.prototype.set = function ($happn, path, data, opts, callback) {

  if (typeof opts == 'function') {
    callback = opts;
    opts = {};
  }

  return $happn.data.set(path, data, opts, function (err, result) {
    callback(err, result);
    if (err == null) $happn.emit(path, data);
  });
};
```
We should check that ops.noPublish is not set before emitting.

**Comment by JensEggers** [comment]
@southbite has agreed to fix this
