### ISSUE TITLE
do not call process.exit() except where not disabled for uncaught exceptions.

### ISSUE THREAD

**Issue by JensEggers** [happner/happner#311]
https://github.com/happner/happner/blob/master/lib/mesh.js#L367

can cause tests to exit prematurely

**Comment by southbite** [comment]
to be clear, if the mesh is not initialized - we just return, ie:

```
var stopmesh = function (mesh, last) {
        if (!mesh._mesh.initialized) return;
        mesh.stop({exitCode: 0, kill: last}, function (e) {
          mesh._mesh.initialized = false;
          if (e) mesh.log.warn('error during stop', e);
        });
      };
```

**Comment by southbite** [comment]
stopmesh is only called on SIGTERM or SIGINT, which means something else is calling SIGTERM or SIGINT in the test - which calls stopmesh and causes a process.exit, not exiting the process means that a SIGTERM or SIGINT wont stop the instance if the mesh is not initialized, could you point me to the offending tests please?

**Comment by JensEggers** [comment]
issue has gone away, probably a testing artifact
