### ISSUE TITLE
Secure Mesh client multiple loging

### ISSUE THREAD

**Issue by cordellcalitz** [happner/happner#56]
When using the mesh client on a secure mesh, updating a user and logging in again causes AccessDenied errors on previously accessible methods

**Comment by southbite** [comment]
Hi Cordell - would you be able to share the code - so we can do a unit test?

On Tue, Dec 8, 2015 at 5:11 PM, cordellcalitz <notifications@github.com>
wrote:

> When using the mesh client on a secure mesh, updating a user and logging
> in again causes AccessDenied errors on previously accessible methods
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/happner/happner/issues/56>.
>



-- 

SIMON BISHOP

DIRECTOR

+27 (0) 83 282 0703

|     simon@tenacious.digital <brianna@tenacious.digital>

twitter: @_tenacious_ <http://www.twitter.com/_tenacious_>

|     skype: sjbishop

201 Salt Circle Arcade, Salt River, Cape Town, 7925

www.tenacious.digital

**Comment by cordellcalitz** [comment]
Hi. I created a branch with a unit test, but I can't push to happner. How should we do this?

**Comment by southbite** [comment]
I make you a contributor :)

On Tuesday, December 8, 2015, cordellcalitz <notifications@github.com>
wrote:

> Hi. I created a branch with a unit test, but I can't push to happner. How
> should we do this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/happner/happner/issues/56#issuecomment-162911771>.
>


-- 

SIMON BISHOP

DIRECTOR

+27 (0) 83 282 0703

|     simon@tenacious.digital <brianna@tenacious.digital>

twitter: @_tenacious_ <http://www.twitter.com/_tenacious_>

|     skype: sjbishop

201 Salt Circle Arcade, Salt River, Cape Town, 7925

www.tenacious.digital

**Comment by southbite** [comment]
done - upload the test - I will take a look ASAP

On Tue, Dec 8, 2015 at 5:55 PM, Simon Bishop <simon@tenacious.digital>
wrote:

> I make you a contributor :)
>
> On Tuesday, December 8, 2015, cordellcalitz <notifications@github.com>
> wrote:
>
>> Hi. I created a branch with a unit test, but I can't push to happner. How
>> should we do this?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/happner/happner/issues/56#issuecomment-162911771>.
>>
>
>
> --
>
> SIMON BISHOP
>
> DIRECTOR
>
> +27 (0) 83 282 0703
>
> |     simon@tenacious.digital <brianna@tenacious.digital>
>
> twitter: @_tenacious_ <http://www.twitter.com/_tenacious_>
>
> |     skype: sjbishop
>
> 201 Salt Circle Arcade, Salt River, Cape Town, 7925
>
> www.tenacious.digital
>
>


-- 

SIMON BISHOP

DIRECTOR

+27 (0) 83 282 0703

|     simon@tenacious.digital <brianna@tenacious.digital>

twitter: @_tenacious_ <http://www.twitter.com/_tenacious_>

|     skype: sjbishop

201 Salt Circle Arcade, Salt River, Cape Town, 7925

www.tenacious.digital

**Comment by cordellcalitz** [comment]
Thanks.

Unit test created in branch: bug/#56
You can just run: mocha test/test-issue/bug-56-mesh-security-login.js

Let me know if anything doesn't work

**Comment by southbite** [comment]
have the test running - will get back to you all tomorrow lunch latest

On Tue, Dec 8, 2015 at 6:03 PM, cordellcalitz <notifications@github.com>
wrote:

> Thanks.
>
> Unit test created in branch: bug/#56
> <https://github.com/happner/happner/issues/56>
> You can just run: mocha test/test-issue/bug-56-mesh-security-login.js
>
> Let me know if anything doesn't work
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/happner/happner/issues/56#issuecomment-162928609>.
>



-- 

SIMON BISHOP

DIRECTOR

+27 (0) 83 282 0703

|     simon@tenacious.digital <brianna@tenacious.digital>

twitter: @_tenacious_ <http://www.twitter.com/_tenacious_>

|     skype: sjbishop

201 Salt Circle Arcade, Salt River, Cape Town, 7925

www.tenacious.digital
