### ISSUE TITLE
endpoints don't reconnect after remote server restart

### ISSUE THREAD

**Issue by JensEggers** [happner/happner#71]
quoth Richard: Endpoints... They don't reconnect. It's become an issue with the tunnel client because it now needs to call createToken() across the exchange on an endpoint connected to the tunnel server. So if the tunnel server is restarted, the endpoint becomes permanently disconnected and createToken() is never again available. So the tunnel is never reconnected. Similarly, when calling a function across a disconnected endpoint's exchange, the call times out - perhaps an immediate error would be more useful.

**Comment by southbite** [comment]
tested in release 1.16.0, https://github.com/happner/happner/blob/master/test/e2-endpoint-reconnection.js
