### ISSUE TITLE
second linkGroup does not update user group

### ISSUE THREAD

**Issue by cordellcalitz** [happner/happner#74]
When calling linkGroup with a user that already has a group linked, the user's groups are not updated to reflect the second group.

**Comment by cordellcalitz** [comment]
Created branch issues/#74 with a failing unit test for this bug

**Comment by southbite** [comment]
released 1.6.8 - fixes this - the problem is actually in happn, we are using a bunch of LRU caches to speed things up - but we are not updating the user cache if a new group is linked
